name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.63.2

      - name: Check generated files are up to date
        run: pixi run check

      # Use ruff-action so we get annotations in the Github UI
      - uses: astral-sh/ruff-action@v3
